//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationEnum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationEnum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISCore.Resources.LocalizationEnum", typeof(LocalizationEnum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled.
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code not exist.
        /// </summary>
        public static string ActivationCodeNotExist {
            get {
                return ResourceManager.GetString("ActivationCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active directory not response.
        /// </summary>
        public static string ActiveDirectoryNotResponse {
            get {
                return ResourceManager.GetString("ActiveDirectoryNotResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active directory organizational unit already exist.
        /// </summary>
        public static string ActiveDirectoryOrganizationalUnitAlreadyExist {
            get {
                return ResourceManager.GetString("ActiveDirectoryOrganizationalUnitAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active directory organizational unit does not exist.
        /// </summary>
        public static string ActiveDirectoryOrganizationalUnitDoesNotExist {
            get {
                return ResourceManager.GetString("ActiveDirectoryOrganizationalUnitDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active directory organizational unit not exist.
        /// </summary>
        public static string ActiveDirectoryOrganizationalUnitNotExist {
            get {
                return ResourceManager.GetString("ActiveDirectoryOrganizationalUnitNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active directory user already exist.
        /// </summary>
        public static string ActiveDirectoryUserAlreadyExist {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance leave.
        /// </summary>
        public static string AdvanceLeave {
            get {
                return ResourceManager.GetString("AdvanceLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string Allowed {
            get {
                return ResourceManager.GetString("Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual leave.
        /// </summary>
        public static string AnnualLeave {
            get {
                return ResourceManager.GetString("AnnualLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key not exist.
        /// </summary>
        public static string APIKeyNotExist {
            get {
                return ResourceManager.GetString("APIKeyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key not valid.
        /// </summary>
        public static string ApiKeyNotValid {
            get {
                return ResourceManager.GetString("ApiKeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already exists.
        /// </summary>
        public static string AplicationAlreadyExists {
            get {
                return ResourceManager.GetString("AplicationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not activate.
        /// </summary>
        public static string ApplicationNotActivate {
            get {
                return ResourceManager.GetString("ApplicationNotActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not available.
        /// </summary>
        public static string ApplicationNotAvailable {
            get {
                return ResourceManager.GetString("ApplicationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not exist.
        /// </summary>
        public static string ApplicationNotExist {
            get {
                return ResourceManager.GetString("ApplicationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not exist.
        /// </summary>
        public static string APPNotExist {
            get {
                return ResourceManager.GetString("APPNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string AppType {
            get {
                return ResourceManager.GetString("AppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank not exist.
        /// </summary>
        public static string BankNotExist {
            get {
                return ResourceManager.GetString("BankNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode not exist.
        /// </summary>
        public static string BarcodeNotExist {
            get {
                return ResourceManager.GetString("BarcodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill already exists.
        /// </summary>
        public static string BillAlreadyExists {
            get {
                return ResourceManager.GetString("BillAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill not exist.
        /// </summary>
        public static string BillNotExist {
            get {
                return ResourceManager.GetString("BillNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the user profile directory.
        /// </summary>
        public static string CannotAccessTheUserProfileDirectory {
            get {
                return ResourceManager.GetString("CannotAccessTheUserProfileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the user profile disk because it is being used by another process.
        /// </summary>
        public static string CannotAccessTheUserProfileDiskBecauseItIsBeingUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("CannotAccessTheUserProfileDiskBecauseItIsBeingUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not exist.
        /// </summary>
        public static string CardNotExist {
            get {
                return ResourceManager.GetString("CardNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not is active.
        /// </summary>
        public static string CardNotIsActive {
            get {
                return ResourceManager.GetString("CardNotIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with that number exists.
        /// </summary>
        public static string CardWithThatNumberExists {
            get {
                return ResourceManager.GetString("CardWithThatNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change is prohibited.
        /// </summary>
        public static string ChangeIsProhibited {
            get {
                return ResourceManager.GetString("ChangeIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client disabled.
        /// </summary>
        public static string ClientDisabled {
            get {
                return ResourceManager.GetString("ClientDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not exist.
        /// </summary>
        public static string ClientNotExist {
            get {
                return ResourceManager.GetString("ClientNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud service.
        /// </summary>
        public static string CloudService {
            get {
                return ResourceManager.GetString("CloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company alias is not correct.
        /// </summary>
        public static string CompanyAliasIsNotCorrect {
            get {
                return ResourceManager.GetString("CompanyAliasIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company already exists.
        /// </summary>
        public static string CompanyAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company data is incorrect.
        /// </summary>
        public static string CompanyDataIsIncorrect {
            get {
                return ResourceManager.GetString("CompanyDataIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company disabled.
        /// </summary>
        public static string CompanyDisabled {
            get {
                return ResourceManager.GetString("CompanyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company IDNO already exists.
        /// </summary>
        public static string CompanyIDNOAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyIDNOAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constantly.
        /// </summary>
        public static string Constantly {
            get {
                return ResourceManager.GetString("Constantly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint violation exception.
        /// </summary>
        public static string ConstraintViolationException {
            get {
                return ResourceManager.GetString("ConstraintViolationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.x.
        /// </summary>
        public static string Contract_7x {
            get {
                return ResourceManager.GetString("Contract_7x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.x.
        /// </summary>
        public static string Contract_8x {
            get {
                return ResourceManager.GetString("Contract_8x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another.
        /// </summary>
        public static string Contract_Another {
            get {
                return ResourceManager.GetString("Contract_Another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Contract_Back {
            get {
                return ResourceManager.GetString("Contract_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa.
        /// </summary>
        public static string Contract_Casa {
            get {
                return ResourceManager.GetString("Contract_Casa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Contract_Client {
            get {
                return ResourceManager.GetString("Contract_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string Contract_CompanyName {
            get {
                return ResourceManager.GetString("Contract_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Contract_Export {
            get {
                return ResourceManager.GetString("Contract_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional.
        /// </summary>
        public static string Contract_FunctionalShortcomings {
            get {
                return ResourceManager.GetString("Contract_FunctionalShortcomings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Contract_Import {
            get {
                return ResourceManager.GetString("Contract_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string Contract_InterfaceFlaws {
            get {
                return ResourceManager.GetString("Contract_InterfaceFlaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Contract_Our {
            get {
                return ResourceManager.GetString("Contract_Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Contract_Production {
            get {
                return ResourceManager.GetString("Contract_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive.
        /// </summary>
        public static string Contract_ProductiveShortcomings {
            get {
                return ResourceManager.GetString("Contract_ProductiveShortcomings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Contract_Sale {
            get {
                return ResourceManager.GetString("Contract_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract not exist.
        /// </summary>
        public static string ContractNotExist {
            get {
                return ResourceManager.GetString("ContractNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new database.
        /// </summary>
        public static string CreatingNewDatabase {
            get {
                return ResourceManager.GetString("CreatingNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server not exist.
        /// </summary>
        public static string DatabaseServerNotExist {
            get {
                return ResourceManager.GetString("DatabaseServerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated.
        /// </summary>
        public static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled by MEV.
        /// </summary>
        public static string DisabledByMEV {
            get {
                return ResourceManager.GetString("DisabledByMEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation not exist.
        /// </summary>
        public static string DocumentationNotExist {
            get {
                return ResourceManager.GetString("DocumentationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate invoice.
        /// </summary>
        public static string DuplicateInvoice {
            get {
                return ResourceManager.GetString("DuplicateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate phone.
        /// </summary>
        public static string DuplicatePhone {
            get {
                return ResourceManager.GetString("DuplicatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used.
        /// </summary>
        public static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erased.
        /// </summary>
        public static string Erased {
            get {
                return ResourceManager.GetString("Erased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connection database.
        /// </summary>
        public static string ErrorConnectionDatabase {
            get {
                return ResourceManager.GetString("ErrorConnectionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error database connect.
        /// </summary>
        public static string ErrorDatabaseConnect {
            get {
                return ResourceManager.GetString("ErrorDatabaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error database server connect.
        /// </summary>
        public static string ErrorDatabaseServerConnect {
            get {
                return ResourceManager.GetString("ErrorDatabaseServerConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error MEV connect.
        /// </summary>
        public static string ErrorMEVConnect {
            get {
                return ResourceManager.GetString("ErrorMEVConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error services down.
        /// </summary>
        public static string ErrorServicesDown {
            get {
                return ResourceManager.GetString("ErrorServicesDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired token.
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal device is activated.
        /// </summary>
        public static string FiscalDeviceIsActivated {
            get {
                return ResourceManager.GetString("FiscalDeviceIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal device is erased.
        /// </summary>
        public static string FiscalDeviceisErased {
            get {
                return ResourceManager.GetString("FiscalDeviceisErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal device not activated.
        /// </summary>
        public static string FiscalDeviceNotActivated {
            get {
                return ResourceManager.GetString("FiscalDeviceNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal device not exist.
        /// </summary>
        public static string FiscalDeviceNotExist {
            get {
                return ResourceManager.GetString("FiscalDeviceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Password&quot; field cannot be the same as the &quot;Number SFS&quot; field.
        /// </summary>
        public static string FiscalizationValidation {
            get {
                return ResourceManager.GetString("FiscalizationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscalized.
        /// </summary>
        public static string Fiscalized {
            get {
                return ResourceManager.GetString("Fiscalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal memory belongs to other device.
        /// </summary>
        public static string FiscalMemoryBelongsToOtherDevice {
            get {
                return ResourceManager.GetString("FiscalMemoryBelongsToOtherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal memory not activated.
        /// </summary>
        public static string FiscalMemoryNotActivated {
            get {
                return ResourceManager.GetString("FiscalMemoryNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal memory wrong ID.
        /// </summary>
        public static string FiscalMemoryWrongID {
            get {
                return ResourceManager.GetString("FiscalMemoryWrongID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal receipt.
        /// </summary>
        public static string FiscalReceipt {
            get {
                return ResourceManager.GetString("FiscalReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal report.
        /// </summary>
        public static string FiscalReport {
            get {
                return ResourceManager.GetString("FiscalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality is disabled.
        /// </summary>
        public static string FunctionalityIsDisabled {
            get {
                return ResourceManager.GetString("FunctionalityIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        public static string Gambling {
            get {
                return ResourceManager.GetString("Gambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML template empty.
        /// </summary>
        public static string HTMLTemplateEmpty {
            get {
                return ResourceManager.GetString("HTMLTemplateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML template error.
        /// </summary>
        public static string HTMLTemplateError {
            get {
                return ResourceManager.GetString("HTMLTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http client error.
        /// </summary>
        public static string HttpClientError {
            get {
                return ResourceManager.GetString("HttpClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible.
        /// </summary>
        public static string Impossible {
            get {
                return ResourceManager.GetString("Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect refresh token.
        /// </summary>
        public static string IncorrectRefreshToken {
            get {
                return ResourceManager.GetString("IncorrectRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate.
        /// </summary>
        public static string Indeterminate {
            get {
                return ResourceManager.GetString("Indeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation ID not found.
        /// </summary>
        public static string InstallationIdNotFound {
            get {
                return ResourceManager.GetString("InstallationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation ID not valid.
        /// </summary>
        public static string InstallationIdNotValid {
            get {
                return ResourceManager.GetString("InstallationIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient amount on card.
        /// </summary>
        public static string InsufficientAmountOnCard {
            get {
                return ResourceManager.GetString("InsufficientAmountOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds.
        /// </summary>
        public static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds on client account.
        /// </summary>
        public static string InsufficientFundsOnClientAccount {
            get {
                return ResourceManager.GetString("InsufficientFundsOnClientAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation platform not exist.
        /// </summary>
        public static string IntsallationPlatformNotExist {
            get {
                return ResourceManager.GetString("IntsallationPlatformNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activate user code.
        /// </summary>
        public static string InvalidActivateUserCode {
            get {
                return ResourceManager.GetString("InvalidActivateUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activation code.
        /// </summary>
        public static string InvalidActivationCode {
            get {
                return ResourceManager.GetString("InvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid company ID.
        /// </summary>
        public static string InvalidCompanyID {
            get {
                return ResourceManager.GetString("InvalidCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid company IDNO.
        /// </summary>
        public static string InvalidCompanyIDNO {
            get {
                return ResourceManager.GetString("InvalidCompanyIDNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid digital signature.
        /// </summary>
        public static string InvalidDigitalSignature {
            get {
                return ResourceManager.GetString("InvalidDigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid external security policy settings.
        /// </summary>
        public static string InvalidExternalSecurityPolicySettings {
            get {
                return ResourceManager.GetString("InvalidExternalSecurityPolicySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format datetime.
        /// </summary>
        public static string InvalidFormatDatetime {
            get {
                return ResourceManager.GetString("InvalidFormatDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        public static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key type.
        /// </summary>
        public static string InvalidKeyType {
            get {
                return ResourceManager.GetString("InvalidKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid license activation code.
        /// </summary>
        public static string InvalidLicenseActivationCode {
            get {
                return ResourceManager.GetString("InvalidLicenseActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        public static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password data.
        /// </summary>
        public static string InvalidPasswordData {
            get {
                return ResourceManager.GetString("InvalidPasswordData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QR.
        /// </summary>
        public static string InvalidQR {
            get {
                return ResourceManager.GetString("InvalidQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid receipt date.
        /// </summary>
        public static string InvalidReceiptDate {
            get {
                return ResourceManager.GetString("InvalidReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid receipt ID.
        /// </summary>
        public static string InvalidReceiptID {
            get {
                return ResourceManager.GetString("InvalidReceiptID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RSA key.
        /// </summary>
        public static string InvalidRSAKey {
            get {
                return ResourceManager.GetString("InvalidRSAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid validation code.
        /// </summary>
        public static string InvalidValidationCode {
            get {
                return ResourceManager.GetString("InvalidValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wallet ID.
        /// </summary>
        public static string InvalidWalletID {
            get {
                return ResourceManager.GetString("InvalidWalletID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is canceled.
        /// </summary>
        public static string InvoiceIsCanceled {
            get {
                return ResourceManager.GetString("InvoiceIsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is paid.
        /// </summary>
        public static string InvoiceIsPaid {
            get {
                return ResourceManager.GetString("InvoiceIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISAuthService not accessible.
        /// </summary>
        public static string ISAuthServiceNotAccessible {
            get {
                return ResourceManager.GetString("ISAuthServiceNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISAuthService not result.
        /// </summary>
        public static string ISAuthServiceNotResult {
            get {
                return ResourceManager.GetString("ISAuthServiceNotResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not new registration.
        /// </summary>
        public static string IsNotNewRegistration {
            get {
                return ResourceManager.GetString("IsNotNewRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string IsOK {
            get {
                return ResourceManager.GetString("IsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not activated.
        /// </summary>
        public static string LicenseNotActivated {
            get {
                return ResourceManager.GetString("LicenseNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not exist.
        /// </summary>
        public static string LicenseNotExist {
            get {
                return ResourceManager.GetString("LicenseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License unit already is fiscal.
        /// </summary>
        public static string LicenseUnitAlreadyIsFiscal {
            get {
                return ResourceManager.GetString("LicenseUnitAlreadyIsFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail service not activated.
        /// </summary>
        public static string MailServiceNotActivated {
            get {
                return ResourceManager.GetString("MailServiceNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field is not set.
        /// </summary>
        public static string MandatoryFieldIsNotSet {
            get {
                return ResourceManager.GetString("MandatoryFieldIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market package not exist.
        /// </summary>
        public static string MarketPackageNotExist {
            get {
                return ResourceManager.GetString("MarketPackageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile applications.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string MobileType {
            get {
                return ResourceManager.GetString("MobileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database.
        /// </summary>
        public static string NewDatabase {
            get {
                return ResourceManager.GetString("NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entity.
        /// </summary>
        public static string NewEntity {
            get {
                return ResourceManager.GetString("NewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New registered.
        /// </summary>
        public static string NewRegistered {
            get {
                return ResourceManager.GetString("NewRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News not activate.
        /// </summary>
        public static string NewsNotActivate {
            get {
                return ResourceManager.GetString("NewsNotActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string NonType {
            get {
                return ResourceManager.GetString("NonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not activated.
        /// </summary>
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fiscal.
        /// </summary>
        public static string NotFiscal {
            get {
                return ResourceManager.GetString("NotFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set company.
        /// </summary>
        public static string NotSetCompany {
            get {
                return ResourceManager.GetString("NotSetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set email.
        /// </summary>
        public static string NotSetEmail {
            get {
                return ResourceManager.GetString("NotSetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set ID fiscal memory.
        /// </summary>
        public static string NotSetIDFiscalMemory {
            get {
                return ResourceManager.GetString("NotSetIDFiscalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set ID SD memory.
        /// </summary>
        public static string NotSetIDSDMemory {
            get {
                return ResourceManager.GetString("NotSetIDSDMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set phone or email.
        /// </summary>
        public static string NotSetPhoneOrEmail {
            get {
                return ResourceManager.GetString("NotSetPhoneOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set printer template.
        /// </summary>
        public static string NotSetPrinterTemplate {
            get {
                return ResourceManager.GetString("NotSetPrinterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On premise desktop applications.
        /// </summary>
        public static string OnPremiseDesktopApplications {
            get {
                return ResourceManager.GetString("OnPremiseDesktopApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent record not exist.
        /// </summary>
        public static string ParentRecordNotExist {
            get {
                return ResourceManager.GetString("ParentRecordNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically.
        /// </summary>
        public static string Periodically {
            get {
                return ResourceManager.GetString("Periodically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal reasons absence.
        /// </summary>
        public static string PersonalReasonsAbsence {
            get {
                return ResourceManager.GetString("PersonalReasonsAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone already used another client.
        /// </summary>
        public static string PhoneAlreadyUsedAnotherClient {
            get {
                return ResourceManager.GetString("PhoneAlreadyUsedAnotherClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone list not exist.
        /// </summary>
        public static string PhoneListNotExist {
            get {
                return ResourceManager.GetString("PhoneListNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number already used from another user.
        /// </summary>
        public static string PhoneNumberAlreadyUsedFromAnotherUser {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyUsedFromAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of sales not exist.
        /// </summary>
        public static string PointOfSalesNotExist {
            get {
                return ResourceManager.GetString("PointOfSalesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of sales settings not exist.
        /// </summary>
        public static string PointOfSalesSettingsNotExist {
            get {
                return ResourceManager.GetString("PointOfSalesSettingsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of sales disabled.
        /// </summary>
        public static string POSDisabled {
            get {
                return ResourceManager.GetString("POSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Priority_Completed {
            get {
                return ResourceManager.GetString("Priority_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Priority_High {
            get {
                return ResourceManager.GetString("Priority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string Priority_In_progress {
            get {
                return ResourceManager.GetString("Priority_In_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Priority_Low {
            get {
                return ResourceManager.GetString("Priority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Priority_Normal {
            get {
                return ResourceManager.GetString("Priority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string Priority_Not_started {
            get {
                return ResourceManager.GetString("Priority_Not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponed.
        /// </summary>
        public static string Priority_Postponed {
            get {
                return ResourceManager.GetString("Priority_Postponed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarely.
        /// </summary>
        public static string Rarely {
            get {
                return ResourceManager.GetString("Rarely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient is not registered.
        /// </summary>
        public static string RecipientIsNotRegistered {
            get {
                return ResourceManager.GetString("RecipientIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exist.
        /// </summary>
        public static string RecordAlreadyExist {
            get {
                return ResourceManager.GetString("RecordAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not disabled.
        /// </summary>
        public static string RecordNotDisabled {
            get {
                return ResourceManager.GetString("RecordNotDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not exist.
        /// </summary>
        public static string RecordNotExist {
            get {
                return ResourceManager.GetString("RecordNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record was used.
        /// </summary>
        public static string RecordWasUsed {
            get {
                return ResourceManager.GetString("RecordWasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycled.
        /// </summary>
        public static string Recycled {
            get {
                return ResourceManager.GetString("Recycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen.
        /// </summary>
        public static string Reopen {
            get {
                return ResourceManager.GetString("Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAAS desktop applications.
        /// </summary>
        public static string SaaSDesktopApplications {
            get {
                return ResourceManager.GetString("SaaSDesktopApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAAS web applications.
        /// </summary>
        public static string SaaSWebApplications {
            get {
                return ResourceManager.GetString("SaaSWebApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema needs to be update.
        /// </summary>
        public static string SchemaNeedsToBeUpdated {
            get {
                return ResourceManager.GetString("SchemaNeedsToBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not set.
        /// </summary>
        public static string ServerIsNotSet {
            get {
                return ResourceManager.GetString("ServerIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service currently suspended.
        /// </summary>
        public static string ServiceCurrentlySuspended {
            get {
                return ResourceManager.GetString("ServiceCurrentlySuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not exist.
        /// </summary>
        public static string ServiceNotExist {
            get {
                return ResourceManager.GetString("ServiceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service receipt.
        /// </summary>
        public static string ServiceReceipt {
            get {
                return ResourceManager.GetString("ServiceReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting 1.
        /// </summary>
        public static string Setting1 {
            get {
                return ResourceManager.GetString("Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting 2.
        /// </summary>
        public static string Setting2 {
            get {
                return ResourceManager.GetString("Setting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting 3.
        /// </summary>
        public static string Setting3 {
            get {
                return ResourceManager.GetString("Setting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sickness.
        /// </summary>
        public static string Sickness {
            get {
                return ResourceManager.GetString("Sickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS campaign not exist.
        /// </summary>
        public static string SMSCampaignNotExist {
            get {
                return ResourceManager.GetString("SMSCampaignNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS campaign set draft.
        /// </summary>
        public static string SMSCampaignSetDraft {
            get {
                return ResourceManager.GetString("SMSCampaignSetDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS service not activated.
        /// </summary>
        public static string SMSServiceNotActivated {
            get {
                return ResourceManager.GetString("SMSServiceNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary key does not exist.
        /// </summary>
        public static string TemporaryKeyDoesNotExist {
            get {
                return ResourceManager.GetString("TemporaryKeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string Terminated {
            get {
                return ResourceManager.GetString("Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount is incorrect.
        /// </summary>
        public static string TheAmountIsIncorrect {
            get {
                return ResourceManager.GetString("TheAmountIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API key does not belong to the company.
        /// </summary>
        public static string TheAPIkeyDoesNotBelongToTheCompany {
            get {
                return ResourceManager.GetString("TheAPIkeyDoesNotBelongToTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client card has no own account.
        /// </summary>
        public static string TheClientCardHasNoOwnAccount {
            get {
                return ResourceManager.GetString("TheClientCardHasNoOwnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the password policy requirements.
        /// </summary>
        public static string ThePasswordDoesNotMeetThePasswordPolicyRequirements {
            get {
                return ResourceManager.GetString("ThePasswordDoesNotMeetThePasswordPolicyRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status cannot be applied.
        /// </summary>
        public static string TheStatusCannotBeApplied {
            get {
                return ResourceManager.GetString("TheStatusCannotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket reply not exist.
        /// </summary>
        public static string TicketReplyNotExist {
            get {
                return ResourceManager.GetString("TicketReplyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not exist.
        /// </summary>
        public static string TiketNotExist {
            get {
                return ResourceManager.GetString("TiketNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time card ID expired.
        /// </summary>
        public static string TimeCardIDExpired {
            get {
                return ResourceManager.GetString("TimeCardIDExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not exist.
        /// </summary>
        public static string TransactionNotExist {
            get {
                return ResourceManager.GetString("TransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating schema.
        /// </summary>
        public static string UpdatingSchema {
            get {
                return ResourceManager.GetString("UpdatingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User disabled.
        /// </summary>
        public static string UserDisabled {
            get {
                return ResourceManager.GetString("UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not found or incorrect e-mail.
        /// </summary>
        public static string UserNameNotFoundOrIncorrectEmail {
            get {
                return ResourceManager.GetString("UserNameNotFoundOrIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not found or incorrect password.
        /// </summary>
        public static string UserNameNotFoundOrIncorrectPassword {
            get {
                return ResourceManager.GetString("UserNameNotFoundOrIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password is incorrect.
        /// </summary>
        public static string UserNameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not activated.
        /// </summary>
        public static string UserNotActivated {
            get {
                return ResourceManager.GetString("UserNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable is null or empty.
        /// </summary>
        public static string VariableIsNullOrEmpty {
            get {
                return ResourceManager.GetString("VariableIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        public static string Viewed {
            get {
                return ResourceManager.GetString("Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB.
        /// </summary>
        public static string WEBType {
            get {
                return ResourceManager.GetString("WEBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work purpose absence.
        /// </summary>
        public static string WorkPurposeAbsence {
            get {
                return ResourceManager.GetString("WorkPurposeAbsence", resourceCulture);
            }
        }
    }
}
